{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "243a1eaf-0a31-4a50-9f8d-5b3d14d52e27",
   "metadata": {},
   "source": [
    "##  7% of Provide region P06 is missing!!! (scenario independent) WHY???\n",
    "\n",
    "\n",
    "\t\t-"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7c689790-cf47-4778-bd4e-0f992fdd7846",
   "metadata": {},
   "source": [
    "**these two glaciers fail, because of missing model_geometry_spinup_historical**\n",
    "\n",
    "RGIId\n",
    "RGI60-10.00006    13 km2\n",
    "RGI60-10.00002    49 km2"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5abdea0c-388d-4e05-867c-edecc8b4c42e",
   "metadata": {},
   "source": [
    "- ok, the issue comes from `No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00002/model_geometry_spinup_historical.nc'`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "cc384b1a-d404-4056-9154-900a25f0b78a",
   "metadata": {},
   "outputs": [],
   "source": [
    "rgi_reg = '14'\n",
    "\n",
    "# RGI glaciers \n",
    "rgi_ids = ['RGI60-10.00002', 'RGI60-10.00005', 'RGI60-10.00001', 'RGI60-10.00006', 'RGI60-10.00007', 'RGI60-10.00004', 'RGI60-10.00003', 'RGI60-10.00008']\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "0705c304-a190-4527-a7cb-39bdc036b23e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-05-16 10:37:19: oggm.cfg: Reading default parameters from the OGGM `params.cfg` configuration file.\n",
      "2023-05-16 10:37:19: oggm.cfg: Multiprocessing switched OFF according to the parameter file.\n",
      "2023-05-16 10:37:19: oggm.cfg: Multiprocessing: using all available processors (N=32)\n",
      "2023-05-16 10:37:19: oggm.cfg: PARAMS['border'] changed from `80` to `160`.\n",
      "2023-05-16 10:37:19: oggm.cfg: Multiprocessing switched ON after user settings.\n",
      "2023-05-16 10:37:19: oggm.cfg: PARAMS['store_model_geometry'] changed from `False` to `True`.\n",
      "2023-05-16 10:37:19: oggm.workflow: init_glacier_directories from prepro level 5 on 8 glaciers.\n",
      "2023-05-16 10:37:19: oggm.workflow: Execute entity tasks [gdir_from_prepro] on 8 glaciers\n",
      "2023-05-16 10:37:20: oggm.cfg: PARAMS['store_diagnostic_variables'] changed from `['volume', 'volume_bsl', 'volume_bwl', 'area', 'length', 'calving', 'calving_rate', 'off_area', 'on_area', 'melt_off_glacier', 'melt_on_glacier', 'liq_prcp_off_glacier', 'liq_prcp_on_glacier', 'snowfall_off_glacier', 'snowfall_on_glacier']` to `['volume', 'volume_bsl', 'area', 'length', 'calving', 'calving_rate', 'off_area', 'on_area', 'melt_off_glacier', 'melt_on_glacier', 'liq_prcp_off_glacier', 'liq_prcp_on_glacier', 'snowfall_off_glacier', 'snowfall_on_glacier', 'model_mb', 'residual_mb', 'snow_bucket']`.\n",
      "2023-05-16 10:37:20: oggm.workflow: init_glacier_directories from prepro level 5 on 8 glaciers.\n",
      "2023-05-16 10:37:20: oggm.workflow: Execute entity tasks [gdir_from_prepro] on 8 glaciers\n",
      "2023-05-16 10:37:21: oggm.workflow: Execute entity tasks [process_cmip_data] on 8 glaciers\n",
      "2023-05-16 10:37:22: oggm.workflow: Execute entity tasks [process_cmip_data] on 8 glaciers\n",
      "2023-05-16 10:37:24: oggm.workflow: Execute entity tasks [process_cmip_data] on 8 glaciers\n",
      "2023-05-16 10:37:25: oggm.workflow: Execute entity tasks [process_cmip_data] on 8 glaciers\n",
      "2023-05-16 10:37:27: oggm.workflow: Execute entity tasks [process_cmip_data] on 8 glaciers\n",
      "2023-05-16 10:37:28: oggm.workflow: Execute entity tasks [process_cmip_data] on 8 glaciers\n",
      "2023-05-16 10:37:30: oggm.workflow: Execute entity tasks [process_cmip_data] on 8 glaciers\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import logging \n",
    "import sys\n",
    "\n",
    "# Libs\n",
    "import xarray as xr\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import geopandas as gpd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Locals\n",
    "import oggm.cfg as cfg\n",
    "from oggm import utils, workflow, tasks\n",
    "# from oggm.shop import gcm_climate\n",
    "import logging\n",
    "# Module logger\n",
    "log = logging.getLogger(__name__)\n",
    "from oggm import entity_task\n",
    "\n",
    "#from func_add import run_hydro_from_2000_ref_area_2000_hist_w5e5_w_overshot_stab_scenarios\n",
    "\n",
    "\n",
    "# normally from oggm.shop.gcm_climate import process_cmip_data\n",
    "# but the changes are not yet updated ...\n",
    "from oggm.shop.gcm_climate import process_gcm_data\n",
    "@entity_task(log, writes=['gcm_data'])\n",
    "def process_cmip_data(gdir, filesuffix='', fpath_temp=None,\n",
    "                      fpath_precip=None, y0=None, y1=None,\n",
    "                      **kwargs):\n",
    "    \"\"\"Read, process and store the CMIP5 and CMIP6 climate data for this glacier.\n",
    "\n",
    "    It stores the data in a format that can be used by the OGGM mass balance\n",
    "    model and in the glacier directory.\n",
    "\n",
    "    Currently, this function is built for the CMIP5 and CMIP6 projection\n",
    "    simulations that are on the OGGM servers.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    filesuffix : str\n",
    "        append a suffix to the filename (useful for ensemble experiments).\n",
    "    fpath_temp : str\n",
    "        path to the temp file\n",
    "    fpath_precip : str\n",
    "        path to the precip file\n",
    "    y0 : int\n",
    "        start year of the CMIP data processing.\n",
    "        Default is None which processes the entire timeseries.\n",
    "        Set this to the beginning of your bias correction/\n",
    "        projection period minus half of bc period\n",
    "        to make process_cmip_data faster.\n",
    "    y1 : int\n",
    "        end year of the CMIP data processing.\n",
    "        Set this to the end of your projection period\n",
    "        plus half of bc period. Default is None to process\n",
    "        the entire time series, same as y0.\n",
    "    **kwargs: any kwarg to be passed to ref:`process_gcm_data`\n",
    "    \"\"\"\n",
    "\n",
    "    # Glacier location\n",
    "    glon = gdir.cenlon\n",
    "    glat = gdir.cenlat\n",
    "\n",
    "    if y0 is not None:\n",
    "        y0 = str(y0)\n",
    "    if y1 is not None:\n",
    "        y1 = str(y1)\n",
    "    # Read the GCM files\n",
    "    with xr.open_dataset(fpath_temp, use_cftime=True) as tempds, \\\n",
    "            xr.open_dataset(fpath_precip, use_cftime=True) as precipds:\n",
    "\n",
    "        # only process and save the gcm data selected --> saves some time!\n",
    "        if (y0 is not None) or (y1 is not None):\n",
    "            tempds = tempds.sel(time=slice(y0, y1))\n",
    "            precipds = precipds.sel(time=slice(y0, y1))\n",
    "        # Check longitude conventions\n",
    "        if tempds.lon.min() >= 0 and glon <= 0:\n",
    "            glon += 360\n",
    "\n",
    "        # Take the closest to the glacier\n",
    "        # Should we consider GCM interpolation?\n",
    "        try:\n",
    "            # if gcms are not flattened, do:\n",
    "            # this is the default, so try this first\n",
    "            temp = tempds.tas.sel(lat=glat, lon=glon, method='nearest')\n",
    "            precip = precipds.pr.sel(lat=glat, lon=glon, method='nearest')\n",
    "        except:\n",
    "            # are the gcms flattened? if yes,\n",
    "            # compute all the distances and choose the\n",
    "            # nearest gridpoint\n",
    "            c_tempds = ((tempds.lon - glon) ** 2 +\n",
    "                 (tempds.lat - glat) ** 2)\n",
    "            c_precipds = ((precipds.lon - glon) ** 2 +\n",
    "                        (precipds.lat - glat) ** 2)\n",
    "            temp_0 = tempds.isel(points=np.argmin(c_tempds.data))\n",
    "            precip_0 = precipds.isel(points=np.argmin(c_precipds.data))\n",
    "            temp = temp_0.tas\n",
    "            temp['lon'] = temp_0.lon\n",
    "            temp['lat'] = temp_0.lat\n",
    "            precip = precip_0.pr\n",
    "            precip['lon'] = precip_0.lon\n",
    "            precip['lat'] = precip_0.lat\n",
    "\n",
    "        # Back to [-180, 180] for OGGM\n",
    "        temp.lon.values = temp.lon if temp.lon <= 180 else temp.lon - 360\n",
    "        precip.lon.values = precip.lon if precip.lon <= 180 else precip.lon - 360\n",
    "\n",
    "        # Convert kg m-2 s-1 to mm mth-1 => 1 kg m-2 = 1 mm !!!\n",
    "        assert 'kg m-2 s-1' in precip.units, 'Precip units not understood'\n",
    "\n",
    "        ny, r = divmod(len(temp), 12)\n",
    "        assert r == 0\n",
    "        dimo = [cfg.DAYS_IN_MONTH[m - 1] for m in temp['time.month']]\n",
    "        precip = precip * dimo * (60 * 60 * 24)\n",
    "\n",
    "    process_gcm_data(gdir, filesuffix=filesuffix, prcp=precip, temp=temp,\n",
    "                     source=filesuffix, **kwargs)\n",
    "\n",
    "\n",
    "###########\n",
    "    \n",
    "# Initialize OGGM and set up the default run parameters\n",
    "cfg.initialize(logging_level='ERROR')\n",
    "rgi_version = '62'\n",
    "\n",
    "cfg.PARAMS['border'] = 160 # changed for OGGM v16\n",
    "\n",
    "# I got a strange KeyError: 'dl_verify_data_cluster.klima.uni-bremen.de' (only for RGI reg 03 and  'gfdl-esm4' 'ssp370')\n",
    "cfg.PARAMS['dl_verify'] = False \n",
    "cfg.PARAMS['continue_on_error'] = False\n",
    "\n",
    "cfg.PARAMS['use_multiprocessing']=True\n",
    "cfg.PARAMS['store_model_geometry'] = True\n",
    "           \n",
    "\n",
    "\n",
    "\n",
    "cfg.PATHS['working_dir'] = utils.gettempdir('OGGM_gcm_run', reset=False)\n",
    "\n",
    "\n",
    "# Go - get the pre-processed glacier directories\n",
    "# TODO -> need to change the preprocessed directory to that here when it is available ... \n",
    "base_url = 'https://cluster.klima.uni-bremen.de/~oggm/gdirs/oggm_v1.6/L3-L5_files/2023.2/elev_bands/W5E5_spinup'\n",
    "# old v2023.1 version: base_url = 'https://cluster.klima.uni-bremen.de/~oggm/gdirs/oggm_v1.6/L3-L5_files/2023.1/elev_bands/W5E5_spinup'\n",
    "gdirs = workflow.init_glacier_directories(rgi_ids, from_prepro_level=5, prepro_border=160,\n",
    "                                          prepro_base_url=base_url, prepro_rgi_version=rgi_version)\n",
    "\n",
    "ALL_DIAGS = ['volume', 'volume_bsl', #'volume_bwl',\n",
    "             'area', 'length',  'calving', 'calving_rate',\n",
    "             'off_area', 'on_area', 'melt_off_glacier',\n",
    "             'melt_on_glacier', 'liq_prcp_off_glacier', 'liq_prcp_on_glacier',\n",
    "             'snowfall_off_glacier', 'snowfall_on_glacier', 'model_mb',\n",
    "             'residual_mb', 'snow_bucket']\n",
    "# Add debug vars\n",
    "cfg.PARAMS['store_diagnostic_variables'] = ALL_DIAGS\n",
    "\n",
    "gdirs = workflow.init_glacier_directories(rgi_ids, from_prepro_level=5, prepro_border=160,\n",
    "                                              prepro_base_url=base_url, prepro_rgi_version=rgi_version)\n",
    "\n",
    "\n",
    "dir_path = 'https://cluster.klima.uni-bremen.de/~lschuster/provide/gfdl-esm2m_oversh_stab_uni_bern/flat/2023.2'\n",
    "scenarios = ['stab_T15',\n",
    "             'oversh_T20OS15',\n",
    "             'oversh_T25OS15',\n",
    "             'oversh_T30OS15',\n",
    "             'stab_T20',\n",
    "             'stab_T25',\n",
    "             'stab_T30']\n",
    "\n",
    "for scenario in scenarios:\n",
    "\n",
    "    fp = f'{dir_path}/gfdl-esm2m_{scenario}_pr_global_monthly_flat_glaciers.nc'\n",
    "    ft = f'{dir_path}/gfdl-esm2m_{scenario}_tas_global_monthly_flat_glaciers.nc'\n",
    "    ft = utils.file_downloader(ft)\n",
    "    fp = utils.file_downloader(fp)\n",
    "    rid = f'_gfdl-esm2m_{scenario}_endyr_2500_bc_2000_2019'\n",
    "    workflow.execute_entity_task(process_cmip_data, gdirs, \n",
    "                                 filesuffix=rid,  # recognize the climate file for later\n",
    "                                 fpath_temp=ft,  # temperature projections\n",
    "                                 fpath_precip=fp,  # precip projections\n",
    "                                 year_range=('2000', '2019'),\n",
    "                                 y0=2000-10,y1=2500) # new this makes the processing a bit faster\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "b0cd0448-551d-483f-8ca6-1ea5b2ab2e1e",
   "metadata": {},
   "outputs": [],
   "source": [
    "gdir = gdirs[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "3ec630f6-8a9e-4268-954f-b97b7f129e45",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-05-16 10:37:59: oggm.cfg: PARAMS['continue_on_error'] changed from `False` to `True`.\n"
     ]
    }
   ],
   "source": [
    "cfg.PARAMS['continue_on_error'] = True\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "eec7d757-b4ed-47cc-ad3c-bc0927265003",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_historical_from_2000_run on RGI60-10.00002: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00002/model_geometry_spinup_historical.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_historical_from_2000_run on RGI60-10.00002: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00002: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00002/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00002: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00002: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00002/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00002: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00002/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00002: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00002: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00002/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00002: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00002/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00002: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00002: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00002/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00002: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00002/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00002: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00002: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00002/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00002: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00002/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00002: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00002: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00002/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00002: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00002/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00002: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00002: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00002/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00002: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00002/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00002: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00002: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00002/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_historical_from_2000_run on RGI60-10.00005: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00005/model_geometry_spinup_historical.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_historical_from_2000_run on RGI60-10.00005: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00005: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00005/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00005: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00005: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00005/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00005: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00005/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00005: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00005: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00005/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00005: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00005/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00005: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00005: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00005/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00005: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00005/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00005: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00005: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00005/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00005: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00005/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00005: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00005: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00005/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00005: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00005/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00005: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00005: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00005/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00005: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00005/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00005: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00005: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00005/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_historical_from_2000_run on RGI60-10.00001: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00001/model_geometry_spinup_historical.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_historical_from_2000_run on RGI60-10.00001: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00001: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00001/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00001: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00001: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00001/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00001: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00001/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00001: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00001: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00001/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00001: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00001/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00001: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00001: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00001/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00001: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00001/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00001: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00001: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00001/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00001: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00001/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00001: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00001: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00001/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00001: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00001/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00001: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00001: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00001/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00001: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00001/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00001: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00001: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00001/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_historical_from_2000_run on RGI60-10.00006: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00006/model_geometry_spinup_historical.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_historical_from_2000_run on RGI60-10.00006: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00006: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00006/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00006: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00006: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00006/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00006: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00006/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00006: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00006: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00006/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00006: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00006/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00006: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00006: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00006/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00006: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00006/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00006: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00006: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00006/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00006: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00006/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00006: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00006: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00006/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00006: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00006/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00006: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00006: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00006/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00006: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00006/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00006: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00006: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00006/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_historical_from_2000_run on RGI60-10.00007: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00007/model_geometry_spinup_historical.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_historical_from_2000_run on RGI60-10.00007: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00007: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00007/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00007: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00007: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00007/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00007: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00007/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00007: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00007: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00007/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00007: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00007/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00007: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00007: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00007/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00007: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00007/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00007: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00007: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00007/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00007: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00007/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00007: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00007: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00007/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00007: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00007/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00007: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00007: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00007/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00007: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00007/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00007: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00007: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00007/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_historical_from_2000_run on RGI60-10.00004: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00004/model_geometry_spinup_historical.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_historical_from_2000_run on RGI60-10.00004: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00004: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00004/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00004: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00004: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00004/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00004: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00004/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00004: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00004: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00004/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00004: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00004/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00004: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00004: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00004/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00004: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00004/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00004: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00004: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00004/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00004: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00004/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00004: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00004: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00004/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00004: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00004/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00004: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00004: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00004/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00004: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00004/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00004: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00004: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00004/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_historical_from_2000_run on RGI60-10.00003: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00003/model_geometry_spinup_historical.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_historical_from_2000_run on RGI60-10.00003: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00003: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00003/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00003: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00003: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00003/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00003: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00003/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00003: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00003: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00003/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00003: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00003/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00003: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00003: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00003/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00003: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00003/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00003: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00003: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00003/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00003: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00003/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00003: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00003: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00003/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00003: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00003/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00003: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00003: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00003/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00003: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00003/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00003: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00003: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00003/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_historical_from_2000_run on RGI60-10.00008: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00008/model_geometry_spinup_historical.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_historical_from_2000_run on RGI60-10.00008: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00008: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00008/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00008: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T15_endyr_2500_bc_2000_2019 on RGI60-10.00008: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00008/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00008: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00008/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00008: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T20OS15_endyr_2500_bc_2000_2019 on RGI60-10.00008: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00008/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00008: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00008/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00008: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T25OS15_endyr_2500_bc_2000_2019 on RGI60-10.00008: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00008/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00008: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00008/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00008: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_oversh_T30OS15_endyr_2500_bc_2000_2019 on RGI60-10.00008: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00008/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00008: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00008/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00008: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T20_endyr_2500_bc_2000_2019 on RGI60-10.00008: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00008/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00008: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00008/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00008: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T25_endyr_2500_bc_2000_2019 on RGI60-10.00008: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00008/model_diagnostics_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: FileNotFoundError occurred during task run_from_climate_data_future_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00008: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00008/model_geometry_historical_from_2000_run.nc'\n",
      "2023-05-16 10:37:59: oggm.core.flowline: InvalidWorkflowError occurred during task run_with_hydro_future_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00008: The run task (run_from_climate_data) did not run successfully.\n",
      "2023-05-16 10:37:59: oggm.utils: FileNotFoundError occurred during task merge_consecutive_run_outputs_merged_from_2000_run_gfdl-esm2m_stab_T30_endyr_2500_bc_2000_2019 on RGI60-10.00008: [Errno 2] No such file or directory: b'/tmp/OGGM/OGGM_gcm_run/per_glacier/RGI60-10/RGI60-10.00/RGI60-10.00008/model_diagnostics_historical_from_2000_run.nc'\n"
     ]
    }
   ],
   "source": [
    "for gdir in gdirs: \n",
    "    tasks.run_with_hydro(gdir, run_task=tasks.run_from_climate_data,\n",
    "                     climate_filename='climate_historical',\n",
    "                     ys=2000, init_model_yr=2000,\n",
    "                     store_monthly_hydro=True,\n",
    "                     init_model_filesuffix='_spinup_historical',\n",
    "                     ref_geometry_filesuffix='_spinup_historical',\n",
    "                     ref_area_yr = 2000,\n",
    "                     output_filesuffix='_historical_from_2000_run')\n",
    "\n",
    "    scenarios = ['stab_T15',\n",
    "                 'oversh_T20OS15',\n",
    "                 'oversh_T25OS15',\n",
    "                 'oversh_T30OS15',\n",
    "                 'stab_T20',\n",
    "                 'stab_T25',\n",
    "                 'stab_T30']\n",
    "    for scenario in scenarios:\n",
    "        rid = f'_gfdl-esm2m_{scenario}_endyr_2500_bc_2000_2019'\n",
    "        tasks.run_with_hydro(gdir,\n",
    "                 run_task=tasks.run_from_climate_data,\n",
    "                             ys=2020, # this is important! Start from 2020 glacier\n",
    "                             ye=2499,\n",
    "                 # use gcm_data, not climate_historical\n",
    "                 climate_filename='gcm_data',\n",
    "                 # use the chosen scenario\n",
    "                 climate_input_filesuffix=rid,\n",
    "                 # we start from the previous run, \n",
    "                 init_model_filesuffix='_historical_from_2000_run',\n",
    "                 ref_geometry_filesuffix='_historical_from_2000_run', \n",
    "                 ref_area_yr = 2000,\n",
    "                 # recognize the run for later\n",
    "                 output_filesuffix=f'_future_run{rid}',\n",
    "                 # add monthly diagnostics\n",
    "                 store_monthly_hydro=True);\n",
    "\n",
    "\n",
    "        utils.merge_consecutive_run_outputs(gdir,\n",
    "                                input_filesuffix_1='_historical_from_2000_run',\n",
    "                                input_filesuffix_2=f'_future_run{rid}',\n",
    "                                output_filesuffix=f'_merged_from_2000_run{rid}',\n",
    "                                delete_input=False,\n",
    "                               ) # we will delete that later\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e354d970-f186-4ee5-9b90-7ed3b860bacf",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
